[package]
name = "rapl_bench-userspace"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
csv = "1.3.1"
ctrlc = "3.4.5"
serde = { version = "1.0.215", features = ["derive"] }
